// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZwAFBr18SWZq99InOwxLstspl2tCS1KE',
    appId: '1:84085241175:android:5c19afe9d87ab5b0f6fa12',
    messagingSenderId: '84085241175',
    projectId: 'ecoswap-64d07',
    databaseURL: 'https://ecoswap-64d07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoswap-64d07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNxxYvFu52ZNMiUglBYBTvGEfwcrlV2PA',
    appId: '1:84085241175:ios:ca66c1a5596a5e38f6fa12',
    messagingSenderId: '84085241175',
    projectId: 'ecoswap-64d07',
    databaseURL: 'https://ecoswap-64d07-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoswap-64d07.appspot.com',
    iosClientId: '84085241175-7neclue3jvggjuge5t5m0frf1683q7gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoSwap',
  );
}
